name: Node.js Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Upload artifacts to S3
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: dist
